# Shell variables
# Generated by 'wal'
wallpaper="/home/natem/Desktop/goya_devourer_wal.jpg"

# Special
background='#0B0F17'
foreground='#c2c3c5'
cursor='#c2c3c5'

# Colors
color0='#0B0F17'
color1='#514224'
color2='#434236'
color3='#534f39'
color4='#66512d'
color5='#5d6152'
color6='#78704b'
color7='#8e9298'
color8='#59616e'
color9='#6C5831'
color10='#5A5948'
color11='#6F6A4D'
color12='#896C3D'
color13='#7C826E'
color14='#A09664'
color15='#c2c3c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
