--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/natem/Desktop/goya_devourer_wal.jpg"

-- Special
background="#0B0F17"
foreground="#c2c3c5"
cursor="#c2c3c5"

-- Colors
color0="#0B0F17"
color1="#514224"
color2="#434236"
color3="#534f39"
color4="#66512d"
color5="#5d6152"
color6="#78704b"
color7="#8e9298"
color8="#59616e"
color9="#6C5831"
color10="#5A5948"
color11="#6F6A4D"
color12="#896C3D"
color13="#7C826E"
color14="#A09664"
color15="#c2c3c5"
