[colors.primary]
background = "#0B0F17"
foreground = "#c2c3c5"

[colors.cursor]
text = "#0B0F17"
cursor = "#c2c3c5"

[colors.vi_mode_cursor]
text = "#0B0F17"
cursor = "#c2c3c5"

[colors.search.matches]
foreground = "#0B0F17"
background = "#c2c3c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#59616e"
background = "#8e9298"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0B0F17"
red = "#514224"
green = "#434236"
yellow = "#534f39"
blue = "#66512d"
magenta = "#5d6152"
cyan = "#78704b"
white = "#8e9298"

[colors.bright]
black = "#59616e"
red = "#6C5831"
green = "#5A5948"
yellow = "#6F6A4D"
blue = "#896C3D"
magenta = "#7C826E"
cyan = "#A09664"
white = "#c2c3c5"

[colors.dim]
black = "#c2c3c5"
red = "#6C5831"
green = "#7C826E"
yellow = "#6F6A4D"
blue = "#896C3D"
magenta = "#5A5948"
cyan = "#A09664"
white = "#59616e"

